-- =======================================================================
-- ULK ATTENDANCE SYSTEM - Sample Data (seed.sql)
-- Auto-generated by tools/generate_seed.py  |  ALL PASSWORD HASHES VERIFIED
--
--   admin@ulk.ac.rw        / Admin@123
--   a.uwase@ulk.ac.rw      / Lect@123   (lecturer 1)
--   e.niyonzima@ulk.ac.rw  / Lect@123   (lecturer 2)
--   c.mukamana@ulk.ac.rw   / Lect@123   (lecturer 3)
--   k.ingabire@ulk.ac.rw   / Stud@123   (student 2024-CS-001)
--   d.uwera@ulk.ac.rw      / Stud@123   (student 2024-CS-002)
--   s.habimana@ulk.ac.rw   / Stud@123   (student 2024-CS-003)
--   a.umutoni@ulk.ac.rw    / Stud@123   (student 2024-CS-004)
--   e.nshimiyimana@ulk.ac.rw / Stud@123 (student 2023-BIT-001)
--   g.mukandayisenga@ulk.ac.rw / Stud@123 (student 2024-IT-001)
-- =======================================================================
USE ulk_attendance_db;

-- users -------------------------------------------------------------
INSERT INTO users (full_name, email, password_hash, role) VALUES
    ('Jean Bosco', 'admin@ulk.ac.rw', '$2b$12$w.uYdrpOde0DC.gtrIMaFe.T8RtsyFFzbC32sNJDO9Pex6VvJa4yG', 'Admin'),
    ('Dr. Alice Uwase', 'a.uwase@ulk.ac.rw', '$2b$12$XXqGnaDCMWnGsQ.fudH8eeM03hAKWS2s7Mewq4N0YWg5gBJtZM7NC', 'Lecturer'),
    ('Mr. Eric Niyonzima', 'e.niyonzima@ulk.ac.rw', '$2b$12$rQwnSW5gJcSH.RXRcfogp.r/0vpGnUR2nAtdYynwDo4ayVEMhHQsy', 'Lecturer'),
    ('Ms. Chantal Mukamana', 'c.mukamana@ulk.ac.rw', '$2b$12$ICl01ZSf7ENTolJQqnjjdO3Jl87GwW/ujuUqpDRIq15svxnJIgd6i', 'Lecturer'),
    ('Kevin Ingabire', 'k.ingabire@ulk.ac.rw', '$2b$12$Qx7FThb0wIkTbZY3J21o1uj5OCbxoL9CTN/5hefsHf5kO9C4dbVAu', 'Student'),
    ('Divine Uwera', 'd.uwera@ulk.ac.rw', '$2b$12$28QuqlYtZgsGWiUIF58wB.ZyADIPgTtHjP5LHp/9If8FAlXOAqK1.', 'Student'),
    ('Samuel Habimana', 's.habimana@ulk.ac.rw', '$2b$12$XMT/GOTKv7S0pUWb4V2kR.QOezEI2kE/SXl/ubHY2rakRLxsUjsqC', 'Student'),
    ('Angelique Umutoni', 'a.umutoni@ulk.ac.rw', '$2b$12$AyPVjx8ytq.nG.6.w6wJj.AimyTWWH/q/7RinGTmOPIniWXc2AhAm', 'Student'),
    ('Eric Nshimiyimana', 'e.nshimiyimana@ulk.ac.rw', '$2b$12$aESKC4VQ2Z9lO/YwubsGbO0AitRJNOktkgefflSMbotAsGez2FqYS', 'Student'),
    ('Grace Mukandayisenga', 'g.mukandayisenga@ulk.ac.rw', '$2b$12$9auW4V6xO64AXNYKUQ4xuO6uY8ezP6zmLyYDHINHBXgql6HQK4q6q', 'Student');

-- students ----------------------------------------------------------
INSERT INTO students (student_reg_no, user_id, major, intake_year) VALUES
    ('2024-CS-001', 5, 'Software Engineering', '2024'),
    ('2024-CS-002', 6, 'Software Engineering', '2024'),
    ('2024-CS-003', 7, 'Software Engineering', '2024'),
    ('2024-CS-004', 8, 'Computer Science', '2024'),
    ('2023-BIT-001', 9, 'Business IT', '2023'),
    ('2024-IT-001', 10, 'Information Technology', '2024');

-- lecturers ---------------------------------------------------------
INSERT INTO lecturers (lecturer_id, user_id) VALUES (1, 2), (2, 3), (3, 4);

-- courses -------------------------------------------------------------
INSERT INTO courses (course_code, title, credits, department) VALUES
    ('CS101', 'Introduction to Programming', 4, 'Computing'),
    ('CS202', 'Data Structures and Algorithms', 4, 'Computing'),
    ('CS305', 'Database Systems', 3, 'Computing'),
    ('BIT201', 'Web Development', 3, 'IT'),
    ('IT110', 'Computer Networks', 3, 'IT');

-- lecturer_courses -----------------------------------------------------
INSERT INTO lecturer_courses (lecturer_id, course_code) VALUES
    (1, 'CS101'),
    (1, 'CS305'),
    (2, 'CS202'),
    (2, 'BIT201'),
    (3, 'IT110');

-- enrollments -----------------------------------------------------------
INSERT INTO enrollments (student_reg_no, course_code) VALUES
    ('2024-CS-001', 'CS101'),
    ('2024-CS-002', 'CS101'),
    ('2024-CS-003', 'CS101'),
    ('2024-CS-004', 'CS101'),
    ('2023-BIT-001', 'CS101'),
    ('2024-IT-001', 'CS101'),
    ('2024-CS-001', 'CS202'),
    ('2024-CS-002', 'CS202'),
    ('2024-CS-003', 'CS202'),
    ('2024-CS-004', 'CS202'),
    ('2024-CS-001', 'CS305'),
    ('2024-CS-002', 'CS305'),
    ('2024-CS-003', 'CS305'),
    ('2024-CS-001', 'BIT201'),
    ('2024-CS-002', 'BIT201'),
    ('2024-CS-003', 'BIT201'),
    ('2023-BIT-001', 'BIT201'),
    ('2024-CS-004', 'IT110'),
    ('2023-BIT-001', 'IT110'),
    ('2024-IT-001', 'IT110');

-- sessions ---------------------------------------------------------------
INSERT INTO sessions (course_code, lecturer_id, session_date, start_time, end_time, status) VALUES
    ('CS101', 1, '2026-07-03', '08:00:00', '10:00:00', 'Closed'),
    ('CS101', 1, '2026-07-10', '08:00:00', '10:00:00', 'Closed'),
    ('CS101', 1, '2026-07-17', '08:00:00', '10:00:00', 'Closed'),
    ('CS101', 1, '2026-07-24', '08:00:00', '10:00:00', 'Closed'),
    ('CS101', 1, '2026-07-31', '08:00:00', '10:00:00', 'Closed'),
    ('CS101', 1, '2026-08-07', '08:00:00', '10:00:00', 'Closed'),
    ('CS101', 1, '2026-08-08', '08:00:00', '10:00:00', 'Open'),
    ('CS305', 1, '2026-07-06', '14:00:00', '16:00:00', 'Closed'),
    ('CS305', 1, '2026-07-13', '14:00:00', '16:00:00', 'Closed'),
    ('CS305', 1, '2026-07-27', '14:00:00', '16:00:00', 'Closed'),
    ('BIT201', 2, '2026-07-08', '09:00:00', '11:00:00', 'Closed'),
    ('BIT201', 2, '2026-07-15', '09:00:00', '11:00:00', 'Closed'),
    ('BIT201', 2, '2026-07-29', '09:00:00', '11:00:00', 'Closed'),
    ('BIT201', 2, '2026-08-05', '09:00:00', '11:00:00', 'Closed'),
    ('IT110', 3, '2026-07-09', '10:00:00', '12:00:00', 'Closed'),
    ('IT110', 3, '2026-07-23', '10:00:00', '12:00:00', 'Closed');

-- attendance_records -----------------------------------------------------
INSERT INTO attendance_records (session_id, student_reg_no, status) VALUES
    (1, '2024-CS-001', 'Present'),
    (1, '2024-CS-002', 'Present'),
    (1, '2024-CS-003', 'Present'),
    (1, '2024-CS-004', 'Present'),
    (1, '2023-BIT-001', 'Present'),
    (1, '2024-IT-001', 'Present'),
    (2, '2024-CS-001', 'Present'),
    (2, '2024-CS-002', 'Present'),
    (2, '2024-CS-003', 'Absent'),
    (2, '2024-CS-004', 'Present'),
    (2, '2023-BIT-001', 'Present'),
    (2, '2024-IT-001', 'Present'),
    (3, '2024-CS-001', 'Present'),
    (3, '2024-CS-002', 'Present'),
    (3, '2024-CS-003', 'Present'),
    (3, '2024-CS-004', 'Present'),
    (3, '2023-BIT-001', 'Late'),
    (3, '2024-IT-001', 'Late'),
    (4, '2024-CS-001', 'Present'),
    (4, '2024-CS-002', 'Present'),
    (4, '2024-CS-003', 'Late'),
    (4, '2024-CS-004', 'Present'),
    (4, '2023-BIT-001', 'Present'),
    (4, '2024-IT-001', 'Present'),
    (5, '2024-CS-001', 'Present'),
    (5, '2024-CS-002', 'Present'),
    (5, '2024-CS-003', 'Absent'),
    (5, '2024-CS-004', 'Absent'),
    (5, '2023-BIT-001', 'Present'),
    (5, '2024-IT-001', 'Present'),
    (6, '2024-CS-001', 'Present'),
    (6, '2024-CS-002', 'Present'),
    (6, '2024-CS-003', 'Excused'),
    (6, '2024-CS-004', 'Present'),
    (6, '2023-BIT-001', 'Present'),
    (6, '2024-IT-001', 'Present'),
    (8, '2024-CS-001', 'Present'),
    (8, '2024-CS-002', 'Present'),
    (8, '2024-CS-003', 'Present'),
    (9, '2024-CS-001', 'Late'),
    (9, '2024-CS-002', 'Present'),
    (9, '2024-CS-003', 'Present'),
    (10, '2024-CS-001', 'Present'),
    (10, '2024-CS-002', 'Present'),
    (10, '2024-CS-003', 'Present'),
    (11, '2024-CS-001', 'Present'),
    (11, '2024-CS-002', 'Present'),
    (11, '2024-CS-003', 'Present'),
    (11, '2023-BIT-001', 'Present'),
    (12, '2024-CS-001', 'Present'),
    (12, '2024-CS-002', 'Late'),
    (12, '2024-CS-003', 'Present'),
    (12, '2023-BIT-001', 'Late'),
    (13, '2024-CS-001', 'Present'),
    (13, '2024-CS-002', 'Present'),
    (13, '2024-CS-003', 'Present'),
    (13, '2023-BIT-001', 'Present'),
    (14, '2024-CS-001', 'Late'),
    (14, '2024-CS-002', 'Present'),
    (14, '2024-CS-003', 'Late'),
    (14, '2023-BIT-001', 'Present'),
    (15, '2024-CS-004', 'Present'),
    (15, '2023-BIT-001', 'Present'),
    (15, '2024-IT-001', 'Present'),
    (16, '2024-CS-004', 'Present'),
    (16, '2023-BIT-001', 'Late'),
    (16, '2024-IT-001', 'Present');

